### ISSUE TITLE
Implement changes so that the service can be used at scale and is resilient

### ISSUE THREAD

**Issue by aks30** [ELEVATE-Project/mentoring-bap-service#2]
**Project Details**

Beckn (short for Beckn protocol) is an open protocol for decentralized commerce. It consists of several specifications for building open e-commerce networks across which sellers and their offers are universally discoverable from any Beckn-enabled app or platform. 

Several particularly famous implementations of Beckn protocol are [ONDC - Open Network Digital Commerce](https://ondc.org/), [Namma Yatri](https://nammayatri.in/), [Unified Health Interface](https://uhi.abdm.gov.in/)

Beckn initiative and efforts in the domain of education and skilling are being undertaken by the[ DSEP project](https://github.com/beckn/DSEP-Specification). DSEP aims to create an Internet of Opportunities i.e. one network that becomes the access point for anyone looking for resources to upskill, jobs, scholarships, and above all mentors who can guide them in their journey.

The DSEP BAP for Mentoring project aims to develop a backend system(combination of micro-services) which when plugged into any existing application that aims to provide mentoring services to its users allows the main application users to access mentors and sessions beyond the current application from various BPP(provider) on the DSEP network.

**Features to be implemented**

1. Create a BAP backend implementation which when plugged into any application providing mentoring capabilities make it DSEP compliant.
2. This is an adapter for the DSEP network, that allows any consumer app to plug in to a DSEP network.

**What exists**

1. A base implementation of integration with the DSEP network - https://github.com/ELEVATE-Project/mentoring-bap-service/tree/c4gt-main
2. API Request response and a high-level backend architecture is defined

**What needs to be built**

1. Extend the base implementation to ensure it can handle volumes and is resilient at scale.

**Learning Path**

**Complexity**
Medium

**Skills Required**
PostgresSQL, NodeJS, Elasticsearch.

**Name of Mentors:**
[@](https://github.com/joffinjoy)Joffin

**Project size**
8 Weeks

**Setup Guide**
[Readme Guide](https://github.com/ELEVATE-Project/mentoring-bap-service/blob/c4gt-main/README.md)

**Product Set Up**
Same as any other NodeJS service setup

**Acceptance Criteria**
A microservice code with documentation on how it can be installed and integrated into any existing application to make it connect with a DSEP-compliant network

**Out of Scope**
A UI interface.

**Milestones**
 

- [ ] Understanding Beckn - https://developers.becknprotocol.io/docs/introduction/introduction/ and https://developers.becknprotocol.io/docs/introduction/video-overview/ 
- [ ] Understanding Beckn transaction flow for mentoring - https://docs.google.com/presentation/d/1CpSXMo4T8f51j5Y_JLRL4FTNNQbO3sm3gUhbXsTGO-E/edit?usp=sharing 
- [ ] BPP Mentoring Implementation - https://drive.google.com/file/d/1ObgMNVmFKtVZlmjW8l7Hb6KVfcziT2iC/view and https://docs.google.com/document/d/1XjRuvDs_4_gGQv7ap07WNDFbC00Ulx1y8zNfp8hYh_4/edit?usp=sharing
- [ ]  Understanding the requirements
- [ ]  Understanding current [BAP Mentoring Service](https://github.com/ELEVATE-Project/mentoring-bap-service)
- [ ]  Come up with BAP backend system architecture.

            1.         Change database from MongoDB to Postgres
            2. 	Implement Sequelize ORM
            3. 	Setup and interface the service with ElasticSearch
            4. 	Use Elasticsearch for search API
            5. 	Fetch from ES or on_search API results
            6. 	Session invalidation in ES

- [ ]  Complete the implementation as per the design.
- [ ]  Create documentation of the implementation to be used by any of the potential adopters.

**Comment by Tanish2002** [comment]
I would like to work on this issue. I'll try to setup the project and get back with queries if any.

**Comment by khanjasir90** [comment]
@aks30 would like to work on this issue and looking forward to submitting a proposal for the same.

**Comment by Sukriti-m** [comment]
Hi @aks30 

I am highly interested in this project. As a junior undergraduate in Computer Science and Engineering, specializing in Backend Web Development, I am excited about contributing to this initiative. With a passion for web development, I am eager to build a backend system that seamlessly integrates with the DSEP network, providing access to mentors and sessions.

I believe in the power of collaboration and its impact on the community. I have a proven track record of contributing to open source programs such as GirlScript Summer of Code, Social Summer of Code, and many more. In fact, I was one of the top contributors in GSSoC'22. These experiences have equipped me with valuable skills in collaborative development, project management, and technical documentation.

With proficiency in PostgresSQL and NodeJS, I am confident in extending the base implementation for scalability. I have started reading the resources that you have provided and will submit my proposal as soon as possible. I look forward to the possibility of joining your esteemed team and making a meaningful impact in the project. I will be grateful for the opportunity to collaborate with mentors and contribute to this project. 

Best Regards,
Sukriti Maurya

**Comment by Deepanshu039** [comment]
Hi @aks30 I would like to work on this project. Also, I will try to submit the proposal as early as possible.

**Comment by shristipandey128** [comment]
I would like to work on this project. 
and plz tell me when we can submit the proposal

**Comment by vinayastar01** [comment]
Hii @aks30 ,
I am really interested to work on this project.

**Comment by karthikeya-io** [comment]
Hi @joffinjoy @aks30 

I've successfully set up the project and begun working on my proposal. While I realize I'm joining a bit later in the process, I'm enthusiastic about contributing to the project and learning from everyone involved. I had done couple of projects with NodeJS and also worked with Elastic search in one of my project. I'm excited to contribute to the project.

I expect to complete my proposal by the end of the day and look forward to receiving your feedback. Please let me know if there's anything specific you'd like me to focus on or any areas you think could benefit from additional attention.

Thank you for your time and consideration.

**Comment by divyanshdave** [comment]
Hi @joffinjoy 
Hi I'm Interested in this project I have prior experience in mongodb ,postgres and elasticsearch along with nodejs and express.I am highly interested in this project. Please let me know if there's anything specific you'd like me to focus on or any areas you think could benefit from additional attention. I look forward to the possibility of joining your esteemed team and making a meaningful impact in the project. I will be grateful for the opportunity to collaborate with mentors and contribute to this project.

Best Regards,
Divyansh Dave

**Comment by joffinjoy** [comment]
@divyanshdave @karthikeya-io @vinayastar01 @shristipandey128

Since this is the last day for submission, please go ahead and make your submissions to unstop as soon as possible.

**Comment by amankumar003** [comment]
@joffinjoy I have submitted the proposal, please review it, hping for the best and hear back from your side 
thank you

**Comment by divyanshdave** [comment]
sure sir

**Comment by shramanpaul** [comment]
@aks30 @joffinjoy is the issue still open for contribution?
