### ISSUE TITLE
Implement a standalone micro improvement  PWA - Unnati

### ISSUE THREAD

**Issue by kiranharidas187** [ELEVATE-Project/mentoring-bap-service#3]
### Project Details

“Unnati” - is a mobile/web application that enables anyone to take up micro-improvements

Unnati helps any person working towards a goal define a digital project, create a plan, and break up their journey into a set of tasks that ultimately help achieve their goal. There exists a library of several projects successfully completed by others which a user can choose from based on what comes closest to what he/she wants to work towards improving. 

Today in Diksha(https://diksha.gov.in/) education leaders(HM, Teachers, etc) have completed close to a million projects using this capability of creating and managing a digital project plan for their own improvement. It supports a wide range of task types (e.g. dependent/hierarchy of tasks, tasks linked to courses that have to be completed, along with quizzes/assessments that have to be taken up as part of the task), and is designed to work well without network connectivity.

With motivations such as awarding digital certificates at the end of the project built in, Unnati with its simple yet powerful construct and design is domain agnostic and truly universal.

###  Features to be implemented

Build a PWA (with truly responsive design that works well on mobile, tab and desktop) leveraging [ml-project-service](https://github.com/shikshalokam/ml-projects-service) and which is compatible with the [ELEVATE](https://elevate.shikshalokam.org/) project [user-service](https://github.com/ELEVATE-Project/user) as well as [notification-service](https://github.com/ELEVATE-Project/notification)

### What exists

- Workflows of creating a digital project plan and tracking the same.
- Backend infrastructure to support a digital project plan creation and management.
- User service and notification service that will help serve the user registration and related workflows.
- A complete vision of how this should be developed.

### What needs to be built

A standalone Unnati PWA 

### Learning Path

**Complexity**
Medium

**Skills Required**
Angular, Ionic, MongoDB, NodeJS, HTML, CSS.

**Name of Mentors:**
Vishwanath - @vishwanath1004

**Project size**
8 weeks

**Product Set Up**
[Ionic Doc
](https://ionicframework.com/docs)

**Acceptance Criteria**
All the flows of micro-improvements should be working fine in the new PWA

**Milestones**

- [ ]  Understanding the requirements
- [ ]  Understanding current project-service, user-service and notification-service
- [ ] Setting up a new ionic app for Unnati
- [ ] Design doc for the frontend implementation
- [ ] Implementation of App
